
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    networks:
      - postgres_service_postgres-net
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - "9092:9092"
      - "5556:5556"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 1
      EXTRA_ARGS: -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent-0.6.jar=5556:/opt/jmx_exporter/jmx_config.yml
    depends_on:
      - zookeeper
    volumes:
      - ./jmx_exporter:/opt/jmx_exporter
    networks:
      - postgres_service_postgres-net

  kafka-exporter:
    image: bitnami/kafka-exporter
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    networks:
      - postgres_service_postgres-net
    command:
      - --kafka.server=kafka:9092
    depends_on:
      - kafka
    restart: on-failure

networks:
  postgres_service_postgres-net:
    external: true
