version: '3.7'
services:
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:2.55.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      #- ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    restart: unless-stopped
    networks:
      - postgres_service_postgres-net

networks:
  postgres_service_postgres-net:
    external: true
