global:
  scrape_interval: 15s

scrape_configs:
  - job_name: postgres_job
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: micrometer_job
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['stub-app:8081']
  - job_name: jmx_exporter_job
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['jmx-exporter:5556']
  - job_name: kafka_exporter_job
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka-exporter:9308']


